### ISSUE TITLE
Notify wicket app from spring @Service

### ISSUE THREAD

**Issue by smiesnyrobert** [MarcGiffing/wicket-spring-boot#171]
Hi,
is here some simple way or example how to notify wicket WebPage from spring @Service?

Eg. 
I have spring @Scheduled task which run every X minutes. After the task end i want notify wicket application that task ended and refresh a component. Should i use Websocket, EventListener or what? Can u provide some good example? 

Thank you for your help. I greatly appreciate it.

**Comment by MarcGiffing** [comment]
I think Websocket is the way to go. 

Take a look at the example project. If a customer is changed or edited a websocket message is sent. It uses the auto configured WebSocketMessageBroadcaster from this project. The current downside is, that it doesn't support any session or user information and everyone is receiving the message.
https://github.com/MarcGiffing/wicket-spring-boot/blob/master/wicket-spring-boot-starter-example/src/main/java/com/giffing/wicket/spring/boot/example/web/pages/customers/create/CustomerCreatePage.java

In the CustomerListPage you can see the component update part:
https://github.com/MarcGiffing/wicket-spring-boot/blob/master/wicket-spring-boot-starter-example/src/main/java/com/giffing/wicket/spring/boot/example/web/pages/customers/CustomerListPage.java

I'm currently trying to extend the WebSocketMessageBroadcaster  to support user/session specific websocket messages.

**Comment by smiesnyrobert** [comment]
Thank you. 
When i tried it from wicket page/panel with @SpringBean WebSocketMessageBroadcaster its working fine. 
But when i want send it from spring @Service with @Autowired WebSocketMessageBroadcaster i got error: **"org.apache.wicket.WicketRuntimeException: There is no application attached to current thread scheduling-1"**
Is something what i am missing? Some configuration or? 

_wicket.external.websocket_=true seems doesnt matter if true or false

I will be very grateful if you help me with this.

**Comment by martin-g** [comment]
What is the full stack trace ? Or at least the line where the `Applciation.get()` is being called.

You can use `Application.get(String)` instead and pass the name of WicketFilter in web.xml

**Comment by smiesnyrobert** [comment]
Code snippet:

`
@Service
public class ActionScheduleService {

    @Autowired
    private WebSocketMessageBroadcaster webSocketMessageBroadcaster;

    public void runAction() {
        webSocketMessageBroadcaster.send(new EventMessage());
    }
}`

**STACKTRACE:**
`org.apache.wicket.WicketRuntimeException: There is no application attached to current thread scheduling-1
	at org.apache.wicket.Application.get(Application.java:213) ~[wicket-core-9.0.0.jar:9.0.0]
	at com.giffing.wicket.spring.boot.starter.web.servlet.websocket.WebSocketMessageSenderDefault.send(WebSocketMessageSenderDefault.java:19) ~[wicket-spring-boot-starter-3.0.4.jar:3.0.4]
	at com.taxximo.web.modelapi.service.ActionScheduleService.runAction(ActionScheduleService.java:108) ~[classes/:na]
	at com.taxximo.web.modelapi.service.ActionScheduleService$$FastClassBySpringCGLIB$$54d6f469.invoke(<generated>) ~[classes/:na]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:771) ~[spring-aop-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749) ~[spring-aop-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:367) ~[spring-tx-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:118) ~[spring-tx-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749) ~[spring-aop-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:691) ~[spring-aop-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at com.taxximo.web.modelapi.service.ActionScheduleService$$EnhancerBySpringCGLIB$$99d93e1c.runAction(<generated>) ~[classes/:na]
	at com.taxximo.web.modelapi.service.scheduler.AutomatScheduler.lambda$triggerAction$1(AutomatScheduler.java:59) ~[classes/:na]
	at java.base/java.util.HashMap.forEach(HashMap.java:1336) ~[na:na]
	at com.taxximo.web.modelapi.service.scheduler.AutomatScheduler.triggerAction(AutomatScheduler.java:58) ~[classes/:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84) ~[spring-context-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) ~[spring-context-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.runAndReset$$$capture(FutureTask.java:305) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java) ~[na:na]
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]`

**Comment by martin-g** [comment]
You can roll out your own version of https://github.com/MarcGiffing/wicket-spring-boot/blob/master/wicket-spring-boot-starter/src/main/java/com/giffing/wicket/spring/boot/starter/web/servlet/websocket/WebSocketMessageSenderDefault.java that uses `Application.get(String)` and use it instead of the default one.

**Comment by smiesnyrobert** [comment]
Thank you very much!!! Great job!

this works for me:

`public class WebSocketMessageSenderDefault extends com.giffing.wicket.spring.boot.starter.web.servlet.websocket.WebSocketMessageSenderDefault {

    @Override
    public void send(IWebSocketPushMessage event) {
        Application application = Application.get("wicket-filter");
        WebSocketSettings webSocketSettings = WebSocketSettings.Holder.get(application);
        IWebSocketConnectionRegistry connectionRegistry = webSocketSettings.getConnectionRegistry();
        Collection<IWebSocketConnection> connections = connectionRegistry.getConnections(application);
        this.log.trace("sending event to {} connections", connections.size());
        Iterator var6 = connections.iterator();

        while(var6.hasNext()) {
            IWebSocketConnection connection = (IWebSocketConnection)var6.next();
            connection.sendMessage(event);
        }
    }
}`

`@Bean
	@Primary
	WebSocketMessageBroadcaster messageBroadcaster(){
		return new WebSocketMessageSenderDefault();
	}`

**Comment by martin-g** [comment]
@MarcGiffing Maybe `WebSocketMessageSenderDefault` could be improved to inject `Application` instead of using `Application.get()` ?!
