### ISSUE TITLE
Wicket Websocket Autoconfiguration

### ISSUE THREAD

**Issue by MarcGiffing** [MarcGiffing/wicket-spring-boot#37]

**Comment by MarcGiffing** [comment]
Only the native JSR356 implementations are supported. Tomcat 8.0+, Tomcat 7.0.47+, Jetty 9.1.0+ and JBoss Wildfly 8.0.0+ (https://ci.apache.org/projects/wicket/guide/7.x/guide/single.html#nativewebsockets)

**Comment by gishi-yama** [comment]
Hi @MarcGiffing, I'm very interested in this project.

I'm trying to run WebSocket sample code using your wicket-spring-boot-starter-example.

I added wicket-native-websocket-javax dependency and `wicket.external.websocket=true` property. Herewith JavaxWebSocketFilter is added to ServletContext on start-up.

However, when endpoint url that is implemented by WebSocketBehavior is called by client side API (e.g. `var ws = new Wicket.WebSocket()` ), the endpoint is always returning status code 404.

Is there any other setting I need to do?

**Comment by martin-g** [comment]
Does `Wicket.WebSocket.send("test")` work?
What web server do you use? With embedded Jetty you need to enable web
socket support explicitly. Check the latest version of Start.java in Wicket
Quickstart archetype.

**Comment by gishi-yama** [comment]
Hi @martin-g. 

No, `Wicket.WebSocket.send("test");` don't work:

```
"WebSocket connection to 'ws://localhost:8080/wicket/websocket?pageId=4&wicket-ajax-baseurl=ws%3F4&wicket-app-name=wicket-filter' failed: Error during WebSocket handshake: Unexpected response code: 404"
at wicket-websocket-jquery.js:69
```

and

```
"Wicket.Ajax:  [WebSocket.send] No open WebSocket connection! Cannot send text message: test"
at wicket-ajax-jquery.js:252
```

In other application that isn't based on wicket-spring-boot, the code is working without problems.

I use embedded tomcat 8.0.30 provided by wicket-spring-boot on localhost.

**Comment by gishi-yama** [comment]
I got a clue.

The same problem has happened in wicket with normal spring-boot application.

I changed wicket-spring-boot-starter-example use [krasa/krasa-wicket-websocket-quickstart](/krasa/krasa-wicket-websocket-quickstart) as a reference. Herewith `Wicket.WebSocket.send("test")` is working.

steps:

1. Add spring-boot-starter-websocket dependency
2. Add ApplicationListener and IWebSocketPushMessage like of [krasa-wicket-websocket-quickstart](/krasa/krasa-wicket-websocket-quickstart/tree/master/src/main/java/krasa/wicket/websocket/service)
3. Attach `@EnableWebSocket` annotation to WicketApplication
4. Define WebSocketConfigurer interface to WicketApplication, and override registerWebSocketHandlers method
5. Define beans of WicketServerEndpointConfig and ServerEndpointExporter

**Comment by MarcGiffing** [comment]
I'm currently investigate the problem. I've got the same error in the browser.  On server side I've got this stacktrace:

`org.apache.catalina.connector.ClientAbortException: java.io.IOException: Eine bestehende Verbindung wurde softwaregesteuert
durch den Hostcomputer abgebrochen
	at org.apache.catalina.connector.OutputBuffer.realWriteBytes(OutputBuffer.java:393) ~[tomcat-embed-core-8.0.30.jar:8.0.30]
	at org.apache.tomcat.util.buf.ByteChunk.flushBuffer(ByteChunk.java:426) ~[tomcat-embed-core-8.0.30.jar:8.0.30]
	at org.apache.catalina.connector.OutputBuffer.doFlush(OutputBuffer.java:342) ~[tomcat-embed-core-8.0.30.jar:8.0.30]
	at org.apache.catalina.connector.OutputBuffer.flush(OutputBuffer.java:317) ~[tomcat-embed-core-8.0.30.jar:8.0.30]
	at org.apache.catalina.connector.CoyoteOutputStream.flush(CoyoteOutputStream.java:110) ~[tomcat-embed-core-8.0.30.jar:8.0.30]
	at com.fasterxml.jackson.core.json.UTF8JsonGenerator.flush(UTF8JsonGenerator.java:1022) ~[jackson-core-2.6.5.jar:2.6.5]
	at com.fasterxml.jackson.databind.ObjectWriter.writeValue(ObjectWriter.java:891) ~[jackson-databind-2.6.5.jar:2.6.5]
	at org.springframework.http.converter.json.AbstractJackson2HttpMessageConverter.writeInternal(AbstractJackson2HttpMessageConverter.java:264) ~[spring-web-4.2.4.RELEASE.jar:4.2.4.RELEASE]
	at org.springframework.http.converter.AbstractGenericHttpMessageConverter.write(AbstractGenericHttpMessageConverter.java:100) ~[spring-web-4.2.4.RELEASE.jar:4.2.4.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.AbstractMessageConverterMethodProcessor.writeWithMessageConverters(AbstractMessageConverterMethodProcessor.java:222) ~[spring-webmvc-4.2.4.RELEASE.jar:4.2.4.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.HttpEntityMethodProcessor.handleReturnValue(HttpEntityMethodProcessor.java:183) ~[spring-webmvc-4.2.4.RELEASE.jar:4.2.4.RELEASE]
	at org.springframework.web.method.support.HandlerMethodReturnValueHandlerComposite.handleReturnValue(HandlerMethodReturnValueHandlerComposite.java:80) ~[spring-web-4.2.4.RELEASE.jar:4.2.4.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:126) ~[spring-webmvc-4.2.4.RELEASE.jar:4.2.4.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:814) ~[spring-webmvc-4.2.4.RELEASE.jar:4.2.4.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:737) ~[spring-webmvc-4.2.4.RELEASE.jar:4.2.4.RELEASE]
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85) ~[spring-webmvc-4.2.4.RELEASE.jar:4.2.4.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:959) ~[spring-webmvc-4.2.4.RELEASE.jar:4.2.4.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:893) ~[spring-webmvc-4.2.4.RELEASE.jar:4.2.4.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:969) ~[spring-webmvc-4.2.4.RELEASE.jar:4.2.4.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:860) ~[spring-webmvc-4.2.4.RELEASE.jar:4.2.4.RELEASE]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:622) ~[tomcat-embed-core-8.0.30.jar:8.0.30]
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:845) ~[spring-webmvc-4.2.4.RELEASE.jar:4.2.4.RELEASE]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729) ~[tomcat-embed-core-8.0.30.jar:8.0.30]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291) ~[tomcat-embed-core-8.0.30.jar:8.0.30]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) ~[tomcat-embed-core-8.0.30.jar:8.0.30]
	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:719) ~[tomcat-embed-core-8.0.30.jar:8.0.30]
	at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:467) ~[tomcat-embed-core-8.0.30.jar:8.0.30]
	at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:390) ~[tomcat-embed-core-8.0.30.jar:8.0.30]
	at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:317) ~[tomcat-embed-core-8.0.30.jar:8.0.30]
	at org.apache.catalina.core.StandardHostValve.custom(StandardHostValve.java:445) [tomcat-embed-core-8.0.30.jar:8.0.30]
	at org.apache.catalina.core.StandardHostValve.status(StandardHostValve.java:304) [tomcat-embed-core-8.0.30.jar:8.0.30]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:181) [tomcat-embed-core-8.0.30.jar:8.0.30]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79) [tomcat-embed-core-8.0.30.jar:8.0.30]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88) [tomcat-embed-core-8.0.30.jar:8.0.30]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:521) [tomcat-embed-core-8.0.30.jar:8.0.30]
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1096) [tomcat-embed-core-8.0.30.jar:8.0.30]
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:674) [tomcat-embed-core-8.0.30.jar:8.0.30]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1500) [tomcat-embed-core-8.0.30.jar:8.0.30]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1456) [tomcat-embed-core-8.0.30.jar:8.0.30]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_45]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_45]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core-8.0.30.jar:8.0.30]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_45]
Caused by: java.io.IOException: Eine bestehende Verbindung wurde softwaregesteuert
durch den Hostcomputer abgebrochen
	at sun.nio.ch.SocketDispatcher.write0(Native Method) ~[na:1.8.0_45]
	at sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:51) ~[na:1.8.0_45]
	at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:93) ~[na:1.8.0_45]
	at sun.nio.ch.IOUtil.write(IOUtil.java:65) ~[na:1.8.0_45]
	at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:471) ~[na:1.8.0_45]
	at org.apache.tomcat.util.net.NioChannel.write(NioChannel.java:124) ~[tomcat-embed-core-8.0.30.jar:8.0.30]
	at org.apache.tomcat.util.net.NioBlockingSelector.write(NioBlockingSelector.java:101) ~[tomcat-embed-core-8.0.30.jar:8.0.30]
	at org.apache.tomcat.util.net.NioSelectorPool.write(NioSelectorPool.java:172) ~[tomcat-embed-core-8.0.30.jar:8.0.30]
	at org.apache.coyote.http11.InternalNioOutputBuffer.writeToSocket(InternalNioOutputBuffer.java:139) ~[tomcat-embed-core-8.0.30.jar:8.0.30]
	at org.apache.coyote.http11.InternalNioOutputBuffer.addToBB(InternalNioOutputBuffer.java:197) ~[tomcat-embed-core-8.0.30.jar:8.0.30]
	at org.apache.coyote.http11.InternalNioOutputBuffer.access$000(InternalNioOutputBuffer.java:41) ~[tomcat-embed-core-8.0.30.jar:8.0.30]
	at org.apache.coyote.http11.InternalNioOutputBuffer$SocketOutputBuffer.doWrite(InternalNioOutputBuffer.java:320) ~[tomcat-embed-core-8.0.30.jar:8.0.30]
	at org.apache.coyote.http11.filters.ChunkedOutputFilter.doWrite(ChunkedOutputFilter.java:118) ~[tomcat-embed-core-8.0.30.jar:8.0.30]
	at org.apache.coyote.http11.AbstractOutputBuffer.doWrite(AbstractOutputBuffer.java:256) ~[tomcat-embed-core-8.0.30.jar:8.0.30]
	at org.apache.coyote.Response.doWrite(Response.java:501) ~[tomcat-embed-core-8.0.30.jar:8.0.30]
	at org.apache.catalina.connector.OutputBuffer.realWriteBytes(OutputBuffer.java:388) ~[tomcat-embed-core-8.0.30.jar:8.0.30]
	... 42 common frames omitted`

**Comment by gishi-yama** [comment]
Here is my example: https://github.com/gishi-yama/wicket-spring-boot-websocket

I hope this will help.

**Comment by MarcGiffing** [comment]
Thanks! It's working now. The following two beans are missing in the starter project:


```
               @Bean
		public ServerEndpointExporter serverEndpointExporter() {
			return new ServerEndpointExporter();
		}
	       @Bean
		public WicketServerEndpointConfig myWicketServerEndpointConfig() {
			return new WicketServerEndpointConfig();
		}
```

I'll update the project today or tomorrow...

**Comment by MarcGiffing** [comment]
Hey @gishi-yama, I've updated the example project! I've created a bean WebSocketEventHandler which will be activated if the websocket configuration is active. Here you have a sendEvent method which can be used to push websocket events. I don't know if the name 'WebSocketEventHandler' is the best choice....

**Comment by MarcGiffing** [comment]
Now we got test failures:

`Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'serverEndpointExporter' defined in class path resource [com/giffing/wicket/spring/boot/starter/web/config/WicketWebInitializerAutoConfig$WebSocketWicketWebInitializerAutoConfiguration.class]: Invocation of init method failed; nested exception is java.lang.IllegalStateException: javax.websocket.server.ServerContainer not available
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1578)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:545)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
        at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)`


`Caused by: java.lang.IllegalStateException: javax.websocket.server.ServerContainer not available
        at org.springframework.util.Assert.state(Assert.java:392)
        at org.springframework.web.socket.server.standard.ServerEndpointExporter.afterPropertiesSet(ServerEndpointExporter.java:102)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1637)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1574)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:545)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)`

**Comment by MarcGiffing** [comment]
https://jira.spring.io/browse/SPR-12340

**Comment by MarcGiffing** [comment]
@martin-g would you give me a hint how the WicketServerEndpointConfig is registered in the default wicket way? In the example from gishi-yama we need Springs ServerEndpointExporter which handles the registration.

**Comment by MarcGiffing** [comment]
Sorry, you've already gave the hint above, thanks! Spring WebSocket dependency is removed. Example should work without it. Tests should be running. I'll add the documenation later.

**Comment by martin-g** [comment]
Usually the web container (Tomcat, Jetty, ...) does a classpath scanning and searches for implementations of some interfaces. I am not sure at the moment whether it looks for `ServerEndpointConfig` or for `Endpoint`.
Embedded Jetty doesn't do such scanning, that's why you have to configure it explicitly: https://github.com/apache/wicket/blob/75422cc984fe2766b0ab2a481c16e032a7904d40/archetypes/quickstart/src/main/resources/archetype-resources/src/test/java/Start.java#L83-L84

Wicket Native WebSocket doesn't integrate with Spring WebSocket for now. I think this would be useful for supporting injection of Spring beans in WebSocket requests/communication. Currently you cannot use session or request scoped beans in Wicket Native WebSockets because Servlet Filters do not intercept the messages in web socket communication and Spring (and any other DI container) cannot export its scoped beans.
