### ISSUE TITLE
Autoconfigure for Wicketstuff Restannoations

### ISSUE THREAD

**Issue by MarcGiffing** [MarcGiffing/wicket-spring-boot#40]

**Comment by MarcGiffing** [comment]
Couldn't inject spring beans when subclassing AbstractRestResource. Injecter.get().inject(this).

Throws error:
Caused by: java.lang.IllegalStateException: Concrete bean could not be received from the application context for class: com.giffing.wicket.spring.boot.example.repository.services.customer.CustomerRepositoryService.
	at org.apache.wicket.spring.SpringBeanLocator.lookupSpringBean(SpringBeanLocator.java:275) ~[wicket-spring-7.1.0.jar:7.1.0]
	at org.apache.wicket.spring.SpringBeanLocator.locateProxyTarget(SpringBeanLocator.java:198) ~[wicket-spring-7.1.0.jar:7.1.0]
	at org.apache.wicket.spring.injection.annot.AnnotProxyFieldValueFactory.getFieldValue(AnnotProxyFieldValueFactory.java:148) ~[wicket-spring-7.1.0.jar:7.1.0]
	at org.apache.wicket.injection.Injector.inject(Injector.java:111) ~[wicket-ioc-7.1.0.jar:7.1.0]
	at org.apache.wicket.spring.injection.annot.SpringComponentInjector.inject(SpringComponentInjector.java:124) ~[wicket-spring-7.1.0.jar:7.1.0]
	at com.giffing.wicket.spring.boot.example.web.pages.customers.CustomerResource.<init>(CustomerResource.java:31) ~[classes/:na]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.8.0_45]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[na:1.8.0_45]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.8.0_45]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422) ~[na:1.8.0_45]
	at java.lang.Class.newInstance(Class.java:442) ~[na:1.8.0_45]
	at org.wicketstuff.rest.utils.mounting.PackageScanner.mountAnnotatedResource(PackageScanner.java:92) ~[wicketstuff-restannotations-7.1.0.jar:7.1.0]
	at org.wicketstuff.rest.utils.mounting.PackageScanner.scanPackage(PackageScanner.java:72) ~[wicketstuff-restannotations-7.1.0.jar:7.1.0]
	... 18 common frames omitted

**Comment by MarcGiffing** [comment]
The problem is that Wicket is initialized before Spring Data JPA. Wicket should be configured at last.

**Comment by MarcGiffing** [comment]
Even if the order changed the bean was not found. The bean was found if the name is provided. (But it couldn't be autowired cause of proxy type problems)

**Comment by MarcGiffing** [comment]
Couldn't even inject the spring application context.

**Comment by MarcGiffing** [comment]
Same issue with SpringReference:

Zero or more than one spring bean candidates. Type: interface com.giffing.wicket.spring.boot.example.repository.services.customer.CustomerRepositoryService, candidates: []
