### ISSUE TITLE
Upgrade to Wicket 7.5.0

### ISSUE THREAD

**Issue by MarcGiffing** [MarcGiffing/wicket-spring-boot#83]
Waiting for Wicket Stuff release...

**Comment by martin-g** [comment]
The release scripts are running ...

**Comment by MarcGiffing** [comment]
There are problems with some tests an the BaseWebSocketBehavior. I'll take a closer look on sunday.

`assert_start_customer_list_page(com.giffing.wicket.spring.boot.example.web.pages.customers.CustomerListIntTest)  Time elapsed: 0.092 sec  <<< ERROR!
org.apache.wicket.WicketRuntimeException: Exception in rendering component: [HtmlHeaderContainer [Component id = _header_]]
	at org.apache.wicket.util.lang.Args.notEmpty(Args.java:64)
	at org.apache.wicket.protocol.ws.api.BaseWebSocketBehavior.renderHead(BaseWebSocketBehavior.java:111)
	at org.apache.wicket.protocol.ws.api.WebSocketBehavior.renderHead(WebSocketBehavior.java:62)
	at org.apache.wicket.Component.internalRenderHead(Component.java:2775)
	at org.apache.wicket.markup.renderStrategy.AbstractHeaderRenderStrategy.renderRootComponent(AbstractHeaderRenderStrategy.java:119)
	at org.apache.wicket.markup.renderStrategy.ChildFirstHeaderRenderStrategy.renderHeader(ChildFirstHeaderRenderStrategy.java:60)
	at org.apache.wicket.markup.html.internal.HtmlHeaderContainer.onComponentTagBody(HtmlHeaderContainer.java:171)
	at org.apache.wicket.markup.html.panel.DefaultMarkupSourcingStrategy.onComponentTagBody(DefaultMarkupSourcingStrategy.java:70)
	at org.apache.wicket.Component.internalRenderComponent(Component.java:2613)
	at org.apache.wicket.MarkupContainer.onRender(MarkupContainer.java:1668)
	at org.apache.wicket.Component.internalRender(Component.java:2413)
	at org.apache.wicket.Component.render(Component.java:2341)
	at org.apache.wicket.MarkupContainer.renderNext(MarkupContainer.java:1526)
	at org.apache.wicket.MarkupContainer.renderAll(MarkupContainer.java:1729)
	at org.apache.wicket.Page.onRender(Page.java:879)
	at org.apache.wicket.markup.html.WebPage.onRender(WebPage.java:141)
	at org.apache.wicket.Component.internalRender(Component.java:2413)
	at org.apache.wicket.Component.render(Component.java:2341)
	at org.apache.wicket.Page.renderPage(Page.java:1018)
	at org.apache.wicket.request.handler.render.WebPageRenderer.renderPage(WebPageRenderer.java:124)
	at org.apache.wicket.request.handler.render.WebPageRenderer.respond(WebPageRenderer.java:236)
	at org.apache.wicket.util.tester.BaseWicketTester$LastPageRecordingPageRendererProvider$1.respond(BaseWicketTester.java:2777)
	at org.apache.wicket.core.request.handler.RenderPageRequestHandler.respond(RenderPageRequestHandler.java:175)
	at org.apache.wicket.request.cycle.RequestCycle$HandlerExecutor.respond(RequestCycle.java:895)
	at org.apache.wicket.request.RequestHandlerStack.execute(RequestHandlerStack.java:64)
	at org.apache.wicket.request.cycle.RequestCycle.execute(RequestCycle.java:265)
	at org.apache.wicket.request.cycle.RequestCycle.processRequest(RequestCycle.java:222)
	at org.apache.wicket.request.cycle.RequestCycle.processRequestAndDetach(RequestCycle.java:293)
	at org.apache.wicket.util.tester.BaseWicketTester.processRequest(BaseWicketTester.java:721)
	at org.apache.wicket.util.tester.BaseWicketTester.processRequest(BaseWicketTester.java:660)
	at org.apache.wicket.util.tester.BaseWicketTester.processRequest(BaseWicketTester.java:632)
	at org.apache.wicket.util.tester.BaseWicketTester.startPage(BaseWicketTester.java:1265)
	at org.apache.wicket.util.tester.BaseWicketTester.startPage(BaseWicketTester.java:1238)
	at com.giffing.wicket.spring.boot.example.web.pages.customers.CustomerListIntTest.assert_start_customer_list_page(CustomerListIntTest.java:31)`

**Comment by martin-g** [comment]
This is a regression.
It is fixed already for 7.6.0.
The only workaround is to copy BaseWebSocketBehavoir#renderHead and replace
notEmpty() with notNull() and remove 'resourceName'
Or deploy with filterPath in web.xml different than /*, e g. /app/*

**Comment by ursjoss** [comment]
Was the intention to actually bump the wicket-version to 7.5.0?

**Comment by MarcGiffing** [comment]
If you add the Wicket Spring Boot Starter dependency you also get the Wicket Core depenency(and Wicket Spring related ones) in the version configured in  the project. And if someone starts a new project the latest version should be used. Thats the main reason. Your are free oder override the dependencies to be independent.

**Comment by ursjoss** [comment]
I know I could handroll my wicket dependencies in my own pom. If possible I'd like to inherit the dependencies on the various wicket modules from the starter though.

I was just asking since the commit message of commit 9a677b9165166c59146eae369603bc06af76d4cc seems to imply you wanted to bump the version. But you still depend on version 7.3.0 in your pom. So I'm (still) not sure if that was intentional or not.

**Comment by MarcGiffing** [comment]
Thanks!!
